
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Stephen Santos

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.
  author: Sun Tzu, The Art of War

# Set this to your main site title. If page doesn't have its own title,
# then this title will be used.
title: vlan101.net


# Following needed for disqus integration
# Set your 'disqus' account name
disqus: vlan101net

# Uncomment if deployed locally
#url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: https://vlan101.net

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
baseurl:

# Change this to your google analytics ID
google_analytics: UA-60428555-1

# Contact form pupublic key
contact_PK: 9851e4fabdfddb61395663c286683a53

##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# MathJax support
math: false

collections:
- definitions

##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
